homepage:
    path:     /
    defaults:
        _controller: FrameworkBundle:Template:template
        template: 'AdymaMainBundle:Default:index.html.twig'
        private: false

hosteleriarm:
    path:     /hosteleria
    defaults:
        _controller: FrameworkBundle:Template:template
        template: 'AdymaMainBundle:Default:hosteleriarmariosyestanterias.html.twig'
        private: false

kcone:
    path:     /barbacoas/one
    defaults:
        _controller: FrameworkBundle:Template:template
        template: 'AdymaMainBundle:Default:one.html.twig'
        private: false