homepage:
    path:     /
    defaults:
        _controller: FrameworkBundle:Template:template
        template: 'AdymaMainBundle:Default:index.html.twig'
        private: false

hosteleria:
    path:     /hosteleria
    defaults:
        _controller: FrameworkBundle:Template:template
        template: 'AdymaMainBundle:Default:hosteleria.html.twig'
        private: false