homepage:
    path:     /
    defaults:
        _controller: FrameworkBundle:Template:template
        template: 'AdymaMainBundle:Default:index.html.twig'
        private: false

hosteleriarm:
    path:     /hosteleria/armarios
    defaults:
        _controller: FrameworkBundle:Template:template
        template: 'AdymaMainBundle:Default:hoste_sub1.html.twig'
        private: false



kcone:
    path:     /barbacoas/one
    defaults:
        _controller: FrameworkBundle:Template:template
        template: 'AdymaMainBundle:Default:one.html.twig'
        private: false