parameters:
#    adyma_main.example.class: Adyma\MainBundle\Example

services:
#    adyma_main.example:
#        class: %adyma_main.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
